### ISSUE TITLE
search conflit with mermaid.js

### ISSUE THREAD

**Issue by gkxk** [next-theme/hexo-generator-searchdb#24]
Please follow this Issue template to provide relevant information, such as source code repository, website URL and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、网站链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using NexT version 8.0 or later.
- [x] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Troubleshooting page of NexT](https://theme-next.js.org/docs/troubleshooting.html).
- [x] I have already searched for current [issues](https://github.com/next-theme/hexo-theme-next/issues), which does not help me.

***

## Actual behavior 

- Links to demo site with this issue:
- Links to repository or source code of the blog:
- Screenshots:
https://theme-next.js.org/docs/tag-plugins/mermaid.html?highlight=mermaid
![image](https://user-images.githubusercontent.com/21279752/166154136-553319a3-00af-4b51-a15c-a838a4c95c8c.png)

https://theme-next.js.org/docs/tag-plugins/mermaid.html?highlight=Hard
![image](https://user-images.githubusercontent.com/21279752/166154122-f5943db6-a2c5-4437-89ce-7bca26b05a09.png)

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

## Other Information 
I have quickfixed this in a stupid way (redirect to `location.origin + location.pathname` if any error is detected)

just want to leave a message, to let anyone related know the issue. 

hope that someone could fix this in a smarter way...

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/next-theme/hexo-generator-searchdb/commit/d416b347186d1577e3b5ea76e22c7b4a0b0e4c5d
Thanks for your feedback

**Comment by gkxk** [comment]
thanks for your work, but still not working..

steps I have tried: 
1, update lib 'hexo-generator-searchdb' to 1.4.1
2, recompile hexo

maybe it's more convincing that you provide a demo page(a blog post url)?
(just to make sure)
@stevenjoezhang

**Comment by stevenjoezhang** [comment]
You can try to edit the code here:

https://github.com/next-theme/hexo-theme-next/blob/d3c78c65edc8225557515d2635267af9d628b91d/_vendors.yml#L135-L138

Change the version to 1.4.1, and then remove the line starts with `integrity: `

**Comment by gkxk** [comment]
amazing, that works. 
much appreciate.
